name: Build and Release
permissions: 
  contents: write
  packages: write

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build Windows executable
        run: go build -ldflags="-s -w -H=windowsgui" -o jhournal.exe .

      - name: Upload Windows release asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: jhournal.exe

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build macOS executable
        run: go build -o jhournal-mac .

      - name: Upload macOS release asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: jhournal-mac

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
            libgl1-mesa-dev \
            libxrandr-dev \
            libxxf86vm-dev \
            libxi-dev \
            libxcursor-dev
      - name: Build Linux executable
        run: go build -o jhournal-linux .

      - name: Upload Linux release asset
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: jhournal-linux