name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -H=windowsgui" -o jhournal.exe .

      - name: Build macOS
        run: GOOS=darwin GOARCH=amd64 go build -o jhournal-mac .

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o jhournal-linux .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            jhournal.exe
            jhournal-mac
            jhournal-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
